/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings` (hash: bd2c791fcdc8b88ca3f841277f4de5a5)
interface __BaseEnv_CloudflareBindings {
  ASSET_FILES: R2Bucket;
  DB: D1Database;
  ASSET_VECTORS: VectorizeIndex;
  GRAPH_VECTORS: VectorizeIndex;
  WORKFLOW_QUEUE: Queue;
  AI: Ai;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./dist/index");
  }
  interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
